name: Update Podcast Feed

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Run every hour

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup PowerShell
      uses: actions/setup-powershell@v2
      with:
        pwsh-version: '7.0' # Specify the PowerShell version you want to use

    - name: Execute PowerShell Script
      run: |
        Import-Module MyPodcastModule.psm1
        Update-PodcastFeed -FeedUrl "https://drpodcast.nu/genstart/feed.xml" -OutputFilename "genstart-feed.xml.xml"

    - name: Commit and Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add updated_feed.xml
        git commit -m "Update podcast feed"
        git push
